---
name: Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Super Duper Linter
        uses: JustinGrote/Super-Duper-Linter@preview
